// Stateless DOM builders for roster cards.
function createRosterCardShell(enemy,selectedId,displayName,assignImage,icons){
 const card=document.createElement('article');card.className='roster-card';card.classList.toggle('defeated',!!enemy.defeated);card.classList.toggle('selected',enemy.instanceId===selectedId);
 const select=document.createElement('button');select.type='button';select.disabled=!!enemy.defeated;select.className='roster-select';select.setAttribute('aria-pressed',String(enemy.instanceId===selectedId));select.setAttribute('aria-label',displayName+'を計算機に登録');
 const heading=document.createElement('span');heading.className='roster-name';const portrait=document.createElement('img');portrait.className='roster-portrait';portrait.alt='';assignImage(portrait,enemy.image);const nameText=document.createElement('span');nameText.className='monster-name-text';nameText.textContent=displayName;heading.append(portrait,nameText);
 if(enemy.boss){const icon=document.createElement('img');icon.className='roster-icon';icon.alt='マップボス';assignImage(icon,'../images/icon/Boss.png');nameText.append(icon);}if(enemy.reflect){const icon=document.createElement('img');icon.className='roster-icon';icon.alt='反撃可能';assignImage(icon,icons.reflect);nameText.append(icon);}
 select.append(heading);const actions=document.createElement('div');actions.className='roster-card-actions';const top=document.createElement('div');top.className='roster-card-top';top.append(select,actions);card.append(top);return {card,select,nameText,actions,top};
}
function createRosterActionButton(className,text,label,disabled=false){const button=document.createElement('button');button.type='button';button.className=className;button.textContent=text;button.disabled=disabled;button.setAttribute('aria-label',label);return button;}
function createRosterMarkControl(enemy,displayName){
 const field=document.createElement('div');field.className='roster-mark';field.title='マーク：左クリックで＋1、右クリックで−1';const button=document.createElement('button');button.type='button';button.className='roster-mark-button';button.disabled=!!enemy.defeated;button.setAttribute('aria-label',displayName+'のマークを増やす');const icon=document.createElement('img');icon.src='../images/icon/'+encodeURIComponent('マーク.png');icon.alt='マーク';button.append(icon);const value=document.createElement('strong');value.textContent=String(enemy.markStacks||0);field.append(button,value);return {field,button};
}

function createRosterStats(enemy,displayName,assignImage,icons,onCommit){
 const stats=document.createElement('span');stats.className='roster-stats';
 [['攻撃',enemy.attack],['防御',enemy.defense],['HP',enemy.hp],['コイン',enemy.coin]].forEach(([key,value])=>{const cell=document.createElement('span');cell.className='roster-stat';if(value!==null){const icon=document.createElement('img');icon.className='roster-icon';icon.alt=key;assignImage(icon,icons[key]);let amount;if(key==='HP'||key==='攻撃'||key==='防御'){const field=key==='HP'?'hp':key==='攻撃'?'attack':'defense',label=key==='HP'?'残りHP':key+'力';amount=document.createElement('input');amount.type='number';amount.disabled=!!enemy.defeated;amount.min='0';amount.step='1';amount.value=value;amount.className='roster-hp';amount.setAttribute('aria-label',displayName+'の'+label);amount.title=label+'を入力'+(key==='HP'?'（0で撃破）':'');amount.addEventListener('focus',()=>amount.select());const commit=(next=amount.value)=>onCommit({key,field,label,input:amount,value:next});amount.addEventListener('change',()=>commit());amount.addEventListener('blur',()=>commit());amount.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();commit();}if(event.key==='Escape'){amount.value=enemy[field];amount.blur();}});const iconButton=document.createElement('button');iconButton.type='button';iconButton.disabled=!!enemy.defeated;iconButton.className='roster-stat-icon';iconButton.title=label+'：左クリックで＋1、右クリックで−1';iconButton.setAttribute('aria-label',displayName+'の'+label+'を増やす');iconButton.append(icon);iconButton.addEventListener('click',()=>commit(enemy[field]+1));iconButton.addEventListener('contextmenu',event=>{event.preventDefault();commit(Math.max(0,enemy[field]-1));});cell.append(iconButton,amount);amount=null;}else{amount=document.createElement('strong');amount.textContent=value;}if(amount)cell.append(icon,amount);}stats.append(cell);});
 return stats;
}
