const $=s=>document.querySelector(s);
const parseCSV=text=>{const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quote){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quote=false;else cell+=ch;}else if(ch==='"')quote=true;else if(ch===','||ch==='\t'){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}const head=(rows.shift()||[]).map(x=>x.replace(/^\uFEFF/,''));return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??''])));};
async function csv(path){const r=await fetch('../csv/'+path,{cache:'no-cache'});if(!r.ok)throw Error(path);return parseCSV(await r.text());}
const state={character:null,level:0,chips:new Set(),numbers:{},modes:{},manual:{atk:0,def:0},currentHp:null,map:''};
let characters=[],chips=[],rules=[],skills=new Map(),category='マーク';
const img=(folder,file)=>'../images/'+folder+'/'+file.split('/').map(encodeURIComponent).join('/');
const num=k=>Math.max(0,Number(state.numbers[k])||0),ownedRules=()=>rules.filter(r=>state.chips.has(String(r.chip_id)));
function condition(r,maxHp){const c=String(r.condition||'').trim();if(!c)return true;if(c==='hp_full')return state.currentHp>=maxHp;if(c==='hp_ratio<0.5')return state.currentHp<maxHp/2;if(c==='hp_ratio<=0.5')return state.currentHp<=maxHp/2;const m=c.match(/^(.+?)(>=|>|<=|<)(-?\d+(?:\.\d+)?)$/);if(m){const v=num(m[1]),n=Number(m[3]);return m[2]==='>='?v>=n:m[2]==='>'?v>n:m[2]==='<='?v<=n:v<n;}return Boolean(state.modes[c]);}
function value(r){const v=Number(r.value)||0,source=num(r.source_key),cap=r.source_cap===''?Infinity:Number(r.source_cap);if(r.formula==='per_stack')return Math.min(source,cap)*v;if(r.formula==='floor_per_unit')return Math.floor(Math.min(source,cap)/(Number(r.unit)||1))*v;return v;}
function stats(){if(!state.character)return null;const c=state.character,l=state.level;let maxHp=Number(c['lv'+l+'_hp'])||0,atk=Number(c['lv'+l+'_atk'])||0,def=Number(c['lv'+l+'_def'])||0,move=Number(c['lv'+l+'_move'])||0;for(const r of ownedRules().filter(r=>r.target==='max_hp'&&['while_owned','while_checked'].includes(r.trigger)))if(condition(r,maxHp))maxHp+=value(r);if(state.currentHp===null)state.currentHp=maxHp;state.currentHp=Math.max(0,Math.min(maxHp,Number(state.currentHp)||0));const out={maxHp,atk,def,move};for(const r of ownedRules().filter(r=>['atk','def','move'].includes(r.target)&&['while_owned','while_checked'].includes(r.trigger)))if(condition(r,maxHp))out[r.target]+=value(r);out.atk+=state.manual.atk||0;out.def+=state.manual.def||0;return out;}
function chipAllowed(c){const cat=c.category||'';if(['マーク','ヒール','コイン','チャージ','共通'].includes(cat))return cat===category;if(category!=='マップ固有')return false;return cat.split('|').includes(state.map);}
function renderCharacters(){const box=$('#character-list');box.replaceChildren(...characters.map(c=>{const x=document.createElement('button');x.className='card';x.innerHTML='<img alt=""><strong></strong>';x.querySelector('img').src=img('character_list',c.list_img);x.querySelector('strong').textContent=c.name;x.onclick=()=>{state.character=c;state.level=0;state.currentHp=null;state.manual={atk:0,def:0};renderSelected();};return x;}));}
function renderChips(){const box=$('#chip-list');box.replaceChildren(...chips.filter(chipAllowed).map(c=>{const x=document.createElement('button');x.className='card'+(state.chips.has(c.id)?' owned':'');x.title=c.effect;x.innerHTML='<img alt=""><strong></strong>';x.querySelector('img').src=img('chip_icon',c.images);x.querySelector('strong').textContent=c.name;x.onclick=()=>{state.chips.has(c.id)?state.chips.delete(c.id):state.chips.add(c.id);renderChips();renderSelected();};return x;}));}
function neededInputs(){const set=new Set();for(const r of ownedRules()){if(r.source_key&&r.source_key!=='追加最大HP')set.add(r.source_key);const c=String(r.condition||'');if(c&&!/[<>]=?/.test(c)&&!['hp_full','hp_ratio<0.5','hp_ratio<=0.5'].includes(c))set.add(c);}return [...set];}
function renderSelected(){if(!state.character){$('#selected').hidden=true;return;}$('#selected').hidden=false;const s=stats(),c=state.character;$('#selected-name').textContent=c.name;$('#level').textContent='Lv.'+state.level;$('#selected-image').src=img('character',c.images);$('#max-hp').textContent=s.maxHp;$('#hp').value=state.currentHp;$('#atk').value=s.atk;$('#def').value=s.def;$('#move').textContent=s.move;$('#ability').textContent=skills.get(c.id)||'';const cond=$('#conditions');cond.replaceChildren(...neededInputs().map(key=>{const wrap=document.createElement('label');wrap.className='condition';const numeric=ownedRules().some(r=>r.source_key===key||String(r.condition||'').startsWith(key)&&/[<>]=?/.test(String(r.condition||'')));if(numeric){wrap.append(document.createTextNode(key));const input=document.createElement('input');input.type='number';input.min='0';input.value=num(key);input.onchange=()=>{state.numbers[key]=Math.max(0,Number(input.value)||0);renderSelected();};wrap.append(input);}else{const input=document.createElement('input');input.type='checkbox';input.checked=!!state.modes[key];input.onchange=()=>{state.modes[key]=input.checked;renderSelected();};wrap.append(input,document.createTextNode(key));}return wrap;}));const owned=$('#owned-chips');owned.replaceChildren(...chips.filter(c=>state.chips.has(c.id)).map(c=>{const x=document.createElement('button');x.title=c.name+'：クリックで外す';const im=document.createElement('img');im.src=img('chip_icon',c.images);im.alt=c.name;x.append(im);x.onclick=()=>{state.chips.delete(c.id);renderChips();renderSelected();};return x;}));}
$('#portrait').onclick=()=>{state.level=(state.level+1)%4;state.currentHp=null;renderSelected();};$('#portrait').oncontextmenu=e=>{e.preventDefault();state.level=(state.level+3)%4;state.currentHp=null;renderSelected();};$('#hp').onchange=e=>{state.currentHp=Math.max(0,Number(e.target.value)||0);renderSelected();};$('#atk').onchange=e=>{const s=stats();state.manual.atk+=(Number(e.target.value)||0)-s.atk;renderSelected();};$('#def').onchange=e=>{const s=stats();state.manual.def+=(Number(e.target.value)||0)-s.def;renderSelected();};
document.querySelectorAll('.tabs button').forEach(x=>x.onclick=()=>{document.querySelectorAll('.tabs button').forEach(y=>y.classList.toggle('active',y===x));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==x.dataset.view);});
const cats=['マーク','ヒール','コイン','チャージ','共通','マップ固有'],ct=$('#chip-tabs');cats.forEach(cat=>{const x=document.createElement('button');x.textContent=cat;x.classList.toggle('active',cat===category);x.onclick=()=>{category=cat;[...ct.children].forEach(y=>y.classList.toggle('active',y===x));renderChips();};ct.append(x);});
Promise.all([csv('character_stats.csv'),csv('chip_list.csv'),csv('chip_stat_rules.csv'),csv('character_skills.csv'),csv('maps_renumbered.csv')]).then(([a,b,c,d,maps])=>{characters=a;chips=b;rules=c;skills=new Map(d.map(x=>[x.id,x.ability]));const select=$('#map-select'),visible=maps.filter(x=>String(x['表示']).trim()==='1');select.replaceChildren(...visible.map(x=>new Option(x['マップ名'],x.map_id)));state.map=select.value;select.onchange=()=>{state.map=select.value;renderChips();renderSelected();};renderCharacters();renderChips();}).catch(e=>{$('#character-status').textContent='CSVの読み込みに失敗しました：'+e.message;});