function setupCharacterNumberPad({selectedPanel}){
 const numberPad=createCharacterNumberPadView();document.body.append(numberPad);
 let numberPadInput=null,numberPadOriginal='',replaceNumberOnDigit=true;
 function positionNumberPad(){if(!numberPadInput||numberPad.hidden)return;const field=numberPadInput.getBoundingClientRect();const dialog=numberPadInput.closest('dialog[open]');const anchor=dialog?dialog.getBoundingClientRect():selectedPanel.contains(numberPadInput)?selectedPanel.getBoundingClientRect():field;const width=numberPad.offsetWidth,height=numberPad.offsetHeight;numberPad.style.left=Math.max(8,Math.min(field.left,window.innerWidth-width-8))+'px';const below=anchor.bottom+6;numberPad.style.top=(below+height<=window.innerHeight-8?below:Math.max(8,anchor.top-height-6))+'px';}
 function closeNumberPad(){document.body.append(numberPad);if(numberPadInput)numberPadInput.removeAttribute('aria-controls');numberPadInput=null;numberPad.hidden=true;}
 function commitNumberPad(){if(!numberPadInput)return;const input=numberPadInput;if(input.value===''&&!input.required)input.value=numberPadOriginal;const changed=input.value!==numberPadOriginal;closeNumberPad();if(changed){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}}
 document.addEventListener('focusin',event=>{if(document.body.classList.contains('mobile-ui'))return;const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=='number'||input.disabled||input.readOnly||input.closest('.battle-card-counter'))return;if(numberPadInput&&numberPadInput!==input)commitNumberPad();const dialog=input.closest('dialog[open]');if(dialog)dialog.append(numberPad);else document.body.append(numberPad);numberPadInput=input;numberPadOriginal=input.value;replaceNumberOnDigit=true;const role=input.classList.contains('roster-hp')?'map':input.closest('.mode-content')?.dataset.role||(selectedPanel.contains(input)?'character':'character');numberPad.className='character-number-pad pad-theme-'+role;input.select();input.setAttribute('aria-controls',numberPad.id);numberPad.hidden=false;positionNumberPad();});
 document.addEventListener('keydown',event=>{if(event.target!==numberPadInput)return;if(event.key==='Enter'){event.preventDefault();commitNumberPad();event.target.blur();}else if(event.key==='Escape'){event.preventDefault();numberPadInput.value=numberPadOriginal;closeNumberPad();event.target.blur();}});
 numberPad.addEventListener('pointerdown',event=>event.preventDefault());
 numberPad.addEventListener('click',event=>{const key=event.target.closest('button[data-key]');if(!key||!numberPadInput)return;const input=numberPadInput,label=key.dataset.key;if(label==='確定'){commitNumberPad();input.blur();return;}if(label==='消去'){input.value=replaceNumberOnDigit?'':input.value.slice(0,-1);}else input.value=(replaceNumberOnDigit?'':input.value)+label;replaceNumberOnDigit=false;input.focus();});
 document.addEventListener('pointerdown',event=>{if(!numberPadInput||event.target===numberPadInput||numberPad.contains(event.target))return;commitNumberPad();},true);
 document.addEventListener('close',event=>{if(event.target instanceof HTMLDialogElement)closeNumberPad();},true);
 window.addEventListener('mobile-ui-change',commitNumberPad);
 window.addEventListener('resize',positionNumberPad);window.addEventListener('scroll',positionNumberPad,true);
}
