"""Build compact game-screen descriptors; source screenshots stay outside git.

Usage: python scripts/build-screen-reader-references.py --screens /path/to/upload
Only visual descriptors and sanitized fixture crops are emitted (no player names).
"""
import argparse, base64, csv, io, json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SIDE = 16
Y = [0, 93, 187, 279]
AVATARS = [(137, 66 + y, 73, 42) for y in Y]
SELF = (181, 445, 139, 116)
HEADER = (431, 84, 43, 42)

def crop(im, box):
    x, y, w, h = box
    return im.crop((x, y, x+w, y+h))

def feature(im):
    return base64.b64encode(im.convert('RGB').resize((SIDE, SIDE), Image.Resampling.BILINEAR).tobytes()).decode()

def mask(im, kind):
    def yes(p):
        r,g,b=p[:3]
        if kind=='red': return r>165 and r>g*1.45 and r>b*1.35
        if kind=='green': return g>170 and g>r*1.3 and g>b*1.25
        if kind=='blue': return b>145 and b>r*1.4 and b>g*1.15
        if kind=='gold': return r>180 and g>110 and b<125 and r>g*1.1
        return min(r,g,b)>215 and max(r,g,b)-min(r,g,b)<35
    return [[int(yes(im.getpixel((x,y)))) for x in range(im.width)] for y in range(im.height)]

def glyphs(im, kind):
    a=mask(im,kind);h=len(a);w=len(a[0]);cols=[sum(row[x] for row in a)>=2 for x in range(w)]
    runs=[];start=None
    for x,active in enumerate(cols+[False]):
        if active and start is None: start=x
        if not active and start is not None:
            pts=[(xx,yy) for yy in range(h) for xx in range(start,x) if a[yy][xx]]
            y0=min(p[1] for p in pts);y1=max(p[1] for p in pts)+1
            if y1-y0>=h*.38 and len(pts)>=12:
                g=Image.new('L',(x-start,y1-y0));g.putdata([a[yy][xx]*255 for yy in range(y0,y1) for xx in range(start,x)])
                data=bytes(int(v>110) for v in g.resize((18,28),Image.Resampling.BILINEAR).getdata())
                runs.append({'data':base64.b64encode(data).decode(),'ratio':g.width/g.height})
            start=None
    return runs

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--screens',required=True);args=parser.parse_args()
    screens={n:Image.open(Path(args.screens)/('IMG_'+n+'.jpeg')).convert('RGB') for n in ['6234','6248','6250','6251','6252']}
    refs={'version':1,'side':SIDE,'characters':[],'chips':[],'digits':[]}
    for n in ['6248','6250','6251','6252']:
        im=screens[n]
        for ident,box in zip(['105','13','21','26'],AVATARS):refs['characters'].append({'id':ident,'kind':'avatar','data':feature(crop(im,box))})
        refs['characters'].append({'id':'105','kind':'self','data':feature(crop(im,SELF))})
    for n,ident in [('6251','105'),('6252','13')]:refs['characters'].append({'id':ident,'kind':'header','data':feature(crop(screens[n],HEADER))})
    for n,ident,x,y in [('6248','30',239,527),('6250','26',239,527),('6251','30',535,352),('6252','26',535,352)]:
        refs['chips'].append({'id':ident,'data':feature(crop(screens[n],(x-18,y-18,36,36)))})
    chip_rows=list(csv.DictReader((ROOT/'csv/chip_list.csv').open(encoding='utf-8-sig'),delimiter='\t'))
    for row in chip_rows:
        im=Image.open(ROOT/'images/chip_icon'/row['images']).convert('RGB');w,h=im.size
        # Match the artwork inside the ring, not the selected/rarity border.
        refs['chips'].append({'id':row['id'],'data':feature(im.crop((w*.17,h*.17,w*.83,h*.83)))})
    samples=[]
    hp={'6234':['9','9','10','9'],'6248':['11','8','7','10'],'6250':['11','12','7','10'],'6251':['11','12','9','10'],'6252':['11','12','9','10']}
    for n,values in hp.items():
        for i,text in enumerate(values):samples.append((n,(116,103+Y[i],49,42),['red','green','blue','gold'][i],text))
    maximum={'6234':['9','9','10','9'],'6248':['11','10','9','10'],'6250':['11','12','9','10'],'6251':['11','12','9','10'],'6252':['11','12','9','10']}
    for n,values in maximum.items():
        for i,text in enumerate(values):samples.append((n,(173,121+Y[i],27,22),['red','green','blue','gold'][i],text))
    for n in ['6251','6252']:
        for box,text in [((542,239,26,37),'1'),((619,239,26,37),'2' if n=='6251' else '1'),((705,239,27,37),'4' if n=='6251' else '5'),((540,157,40,58),'6'),((1177,566,28,40),'3')]:samples.append((n,box,'white',text))
        for i,text in enumerate(['17','16','24','9']):samples.append((n,(235,98+Y[i],27,24),'white',text))
    for n,box,kind,text in samples:
        gs=glyphs(crop(screens[n],box),kind)
        if len(gs)!=len(text):print('Skipped ambiguous reference',n,box,text,len(gs));continue
        refs['digits'].extend({'digit':d,**g} for d,g in zip(text,gs))
    out=ROOT/'08_screen_reader/js/screen-reader-references.js'
    out.write_text('// Generated by scripts/build-screen-reader-references.py; no full screenshots.\nwindow.ScreenReaderReferences='+json.dumps(refs,separators=(',',':'))+';\n')
    fixtures=ROOT/'tests/fixtures/screen-reader';fixtures.mkdir(parents=True,exist_ok=True)
    # Retain only recognition areas; erase names, chat, cards and the map.
    for n in ['6248','6250','6251','6252']:
        im=screens[n];safe=Image.new('RGB',im.size,(20,20,20))
        boxes=AVATARS+[SELF,HEADER]+[(116,103+y,85,42) for y in Y]+[(235,98+y,27,24) for y in Y]+[(268,98+y,65,26) for y in Y]
        if n in ['6248','6250']:boxes += [(125,430,435,40),(165,498,288,187)]
        else:boxes += [(542,239,26,37),(619,239,26,37),(705,239,27,37),(465,324,286,184)]
        for box in boxes:
            x,y,_,_=box;safe.paste(crop(im,box),(x,y))
        b=io.BytesIO();safe.save(b,format='PNG')
        (fixtures/(n+'.json')).write_text(json.dumps({'image':'data:image/png;base64,'+base64.b64encode(b.getvalue()).decode()}))
    print('Built',len(refs['characters']),'character references,',len(refs['chips']),'chips,',len(refs['digits']),'digit shapes')

if __name__=='__main__':main()
